name: Integration
on: [push, pull_request]
jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable
        components: rustfmt
    - name: Check Formatting
      run: cargo fmt --all -- --check

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable, nightly]
        features: ['', '--all-features', "--features image,rusttype"]
    steps:
    - uses: hecrj/setup-rust-action@v1.2.0
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@master
    - name: Clippy
      run: cargo test ${{ matrix.options }}

  clippy:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable]
        features: ['', '--all-features', "--features image,rusttype"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: hecrj/setup-rust-action@v1.2.0
      with:
        rust-version: ${{ matrix.rust }}
        components: clippy
    - uses: actions/checkout@master
    - name: Clippy
      run: cargo clippy ${{ matrix.features }} -- -D warnings
